#!/usr/bin/env node
/**
 * Vendors the Nullthrone design-system webfonts into assets/fonts/ so the
 * site runs with zero runtime downloads — the same rule the vendored
 * three.js and the fetched planet textures follow.
 *
 * Pulls the Google Fonts CSS for each family, keeps the `latin` and
 * `latin-ext` subsets (everything the German/English UI needs), downloads
 * the woff2 binaries and rewrites the @font-face rules against local
 * paths into styles/tokens/fonts.css. `assets/fonts/manifest.json`
 * records the exact source URL per file.
 *
 * Usage: node tools/fetch-fonts.mjs
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const fontsDir = join(root, 'assets', 'fonts');
const cssOut = join(root, 'styles', 'tokens', 'fonts.css');

/**
 * Families used by the design system tokens. All three are variable fonts,
 * so we ask for the weight *range* the tokens span: Google then serves one
 * file per subset instead of one identical copy per discrete weight.
 */
const FAMILIES = [
  { name: 'Jost', file: 'jost', wght: '300..700' },
  { name: 'Public Sans', file: 'public-sans', wght: '400..700' },
  { name: 'JetBrains Mono', file: 'jetbrains-mono', wght: '400..600' },
];

const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

// Google Fonts serves woff2 only to browsers that advertise support.
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

async function get(url, asBuffer = false) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} — ${url}`);
  return asBuffer ? Buffer.from(await res.arrayBuffer()) : res.text();
}

/** Splits the Google CSS into { subset, weight, style, srcUrl, unicodeRange }. */
function parseFaces(css) {
  const faces = [];
  const re = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g;
  for (const [, subset, block] of css.matchAll(re)) {
    const pick = (key) => block.match(new RegExp(`${key}:\\s*([^;]+);`))?.[1].trim();
    const srcUrl = block.match(/url\(([^)]+)\)/)?.[1];
    if (!srcUrl) continue;
    faces.push({
      subset,
      weight: pick('font-weight'),
      style: pick('font-style'),
      unicodeRange: pick('unicode-range'),
      srcUrl,
    });
  }
  return faces;
}

mkdirSync(fontsDir, { recursive: true });

const rules = [];
const manifest = {};

for (const family of FAMILIES) {
  const api = `https://fonts.googleapis.com/css2?family=${
    encodeURIComponent(family.name).replace(/%20/g, '+')
  }:wght@${family.wght}&display=swap`;
  console.log(`Fetching ${family.name} …`);
  const faces = parseFaces(await get(api)).filter((f) => KEEP_SUBSETS.has(f.subset));

  for (const face of faces) {
    const base = `${family.file}-${face.subset}.woff2`;
    console.log(`  ${base}`);
    writeFileSync(join(fontsDir, base), await get(face.srcUrl, true));
    manifest[`assets/fonts/${base}`] = face.srcUrl;
    rules.push(
      `@font-face{font-family:'${family.name}';font-style:${face.style};font-weight:${face.weight};` +
      `font-display:swap;src:url('../../assets/fonts/${base}') format('woff2');` +
      `unicode-range:${face.unicodeRange}}`
    );
  }
}

writeFileSync(join(fontsDir, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);
writeFileSync(cssOut, [
  '/* Nullthrone design-system webfonts — vendored, no runtime downloads.',
  ' * Generated by tools/fetch-fonts.mjs; see assets/fonts/manifest.json for sources.',
  ' * Jost and Public Sans and JetBrains Mono are SIL Open Font License 1.1. */',
  ...rules,
  '',
].join('\n'));

console.log(`\nWrote ${rules.length} @font-face rules to styles/tokens/fonts.css`);
