#!/usr/bin/env node
/**
 * Builds the star-catalog subset from the HYG database (v4.1, CC-BY-SA
 * 4.0, https://github.com/astronexus/HYG-Database):
 *   - assets/stars/hyg_subset.json   (~9k stars: mag <= 6.5 or within 5 pc)
 *   - src/data/brightFallback.js     (~90 brightest, embedded fallback)
 *
 * Parallel arrays keep the JSON compact: ra (deg), dec (deg), d (pc),
 * absmag, ci (B-V). Apparent magnitudes per observer are derived at
 * runtime, which is what makes per-system parallax skies work.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const URL = 'https://raw.githubusercontent.com/astronexus/HYG-Database/main/hyg/CURRENT/hygdata_v41.csv';

console.log('downloading HYG v4.1 (~34 MB) ...');
const res = await fetch(URL, { signal: AbortSignal.timeout(180000) });
if (!res.ok) {
  console.error(`HTTP ${res.status} — aborting, runtime will fall back to embedded bright stars`);
  process.exit(1);
}
const csv = await res.text();
const lines = csv.split('\n');
const unq = (s) => (s ?? '').trim().replace(/^"|"$/g, '');
const header = lines[0].split(',').map(unq);
const col = Object.fromEntries(header.map((h, i) => [h, i]));
const need = ['ra', 'dec', 'dist', 'mag', 'absmag', 'ci', 'proper', 'id'];
for (const n of need) {
  if (col[n] === undefined) {
    console.error(`column ${n} missing — header: ${header.join(',')}`);
    process.exit(1);
  }
}

const out = { n: 0, ra: [], dec: [], d: [], absmag: [], ci: [], names: {} };
let kept = 0;
for (let i = 1; i < lines.length; i++) {
  const line = lines[i];
  if (!line) continue;
  const parts = line.split(',');
  const dist = parseFloat(unq(parts[col.dist]));
  const mag = parseFloat(unq(parts[col.mag]));
  if (!isFinite(dist) || !isFinite(mag)) continue;
  if (dist <= 0 || dist >= 100000) continue;         // unknown distance
  if (dist < 1e-4) continue;                          // the Sun itself
  if (mag > 6.5 && dist > 5) continue;                // keep naked-eye + all nearby
  const ra = parseFloat(unq(parts[col.ra])) * 15;     // hours -> degrees
  const dec = parseFloat(unq(parts[col.dec]));
  const absmag = parseFloat(unq(parts[col.absmag]));
  const ci = parseFloat(unq(parts[col.ci]));
  const proper = unq(parts[col.proper]);
  out.ra.push(+ra.toFixed(4));
  out.dec.push(+dec.toFixed(4));
  out.d.push(+dist.toFixed(4));
  out.absmag.push(+absmag.toFixed(3));
  out.ci.push(isFinite(ci) ? +ci.toFixed(3) : 0.5);
  if (proper) out.names[kept] = proper;
  kept++;
}
out.n = kept;

mkdirSync(join(root, 'assets', 'stars'), { recursive: true });
const jsonPath = join(root, 'assets', 'stars', 'hyg_subset.json');
writeFileSync(jsonPath, JSON.stringify(out));
console.log(`kept ${kept} stars -> ${jsonPath} (${(JSON.stringify(out).length / 1024).toFixed(0)} KB)`);

// Embedded fallback: brightest ~90 by apparent magnitude from Sol.
const idx = [...Array(kept).keys()];
idx.sort((a, b) => {
  const mA = out.absmag[a] + 5 * (Math.log10(out.d[a]) - 1);
  const mB = out.absmag[b] + 5 * (Math.log10(out.d[b]) - 1);
  return mA - mB;
});
const top = idx.slice(0, 90);
const fb = top.map((i) => ({
  ra: out.ra[i], dec: out.dec[i], d: out.d[i], absmag: out.absmag[i], ci: out.ci[i],
  ...(out.names[i] ? { name: out.names[i] } : {}),
}));
const fbPath = join(root, 'src', 'data', 'brightFallback.js');
writeFileSync(fbPath, `/** Generated by tools/fetch-stars.mjs from HYG v4.1 (CC-BY-SA 4.0). Embedded fallback when assets/stars/hyg_subset.json is unavailable. */
export const BRIGHT_FALLBACK = ${JSON.stringify(fb)};
`);
console.log(`embedded fallback (${fb.length} stars) -> ${fbPath}`);
